/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PressRouteImport } from './routes/press'
import { Route as MeRouteImport } from './routes/me'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ForCreatorsRouteImport } from './routes/for-creators'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MeIndexRouteImport } from './routes/me.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as OnboardingCreatorRouteImport } from './routes/onboarding.creator'
import { Route as MeSubscriptionsRouteImport } from './routes/me.subscriptions'
import { Route as MeSettingsRouteImport } from './routes/me.settings'
import { Route as MeFollowingRouteImport } from './routes/me.following'
import { Route as MeDownloadsRouteImport } from './routes/me.downloads'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalDmcaRouteImport } from './routes/legal.dmca'
import { Route as LegalCreatorAgreementRouteImport } from './routes/legal.creator-agreement'
import { Route as DashboardTiersRouteImport } from './routes/dashboard.tiers'
import { Route as DashboardSubscribersRouteImport } from './routes/dashboard.subscribers'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardPayoutsRouteImport } from './routes/dashboard.payouts'
import { Route as DashboardFilesRouteImport } from './routes/dashboard.files'
import { Route as DashboardAnnouncementsRouteImport } from './routes/dashboard.announcements'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as CSlugRouteImport } from './routes/c.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForCreatorsRoute = ForCreatorsRouteImport.update({
  id: '/for-creators',
  path: '/for-creators',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeIndexRoute = MeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MeRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const OnboardingCreatorRoute = OnboardingCreatorRouteImport.update({
  id: '/onboarding/creator',
  path: '/onboarding/creator',
  getParentRoute: () => rootRouteImport,
} as any)
const MeSubscriptionsRoute = MeSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => MeRoute,
} as any)
const MeSettingsRoute = MeSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MeRoute,
} as any)
const MeFollowingRoute = MeFollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => MeRoute,
} as any)
const MeDownloadsRoute = MeDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => MeRoute,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LegalRoute,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LegalRoute,
} as any)
const LegalDmcaRoute = LegalDmcaRouteImport.update({
  id: '/dmca',
  path: '/dmca',
  getParentRoute: () => LegalRoute,
} as any)
const LegalCreatorAgreementRoute = LegalCreatorAgreementRouteImport.update({
  id: '/creator-agreement',
  path: '/creator-agreement',
  getParentRoute: () => LegalRoute,
} as any)
const DashboardTiersRoute = DashboardTiersRouteImport.update({
  id: '/tiers',
  path: '/tiers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSubscribersRoute = DashboardSubscribersRouteImport.update({
  id: '/subscribers',
  path: '/subscribers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPayoutsRoute = DashboardPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFilesRoute = DashboardFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnnouncementsRoute = DashboardAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/explore': typeof ExploreRoute
  '/for-creators': typeof ForCreatorsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/legal': typeof LegalRouteWithChildren
  '/me': typeof MeRouteWithChildren
  '/press': typeof PressRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roadmap': typeof RoadmapRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/c/$slug': typeof CSlugRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/announcements': typeof DashboardAnnouncementsRoute
  '/dashboard/files': typeof DashboardFilesRoute
  '/dashboard/payouts': typeof DashboardPayoutsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/subscribers': typeof DashboardSubscribersRoute
  '/dashboard/tiers': typeof DashboardTiersRoute
  '/legal/creator-agreement': typeof LegalCreatorAgreementRoute
  '/legal/dmca': typeof LegalDmcaRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/me/downloads': typeof MeDownloadsRoute
  '/me/following': typeof MeFollowingRoute
  '/me/settings': typeof MeSettingsRoute
  '/me/subscriptions': typeof MeSubscriptionsRoute
  '/onboarding/creator': typeof OnboardingCreatorRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/me/': typeof MeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/explore': typeof ExploreRoute
  '/for-creators': typeof ForCreatorsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/legal': typeof LegalRouteWithChildren
  '/press': typeof PressRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roadmap': typeof RoadmapRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/c/$slug': typeof CSlugRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/announcements': typeof DashboardAnnouncementsRoute
  '/dashboard/files': typeof DashboardFilesRoute
  '/dashboard/payouts': typeof DashboardPayoutsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/subscribers': typeof DashboardSubscribersRoute
  '/dashboard/tiers': typeof DashboardTiersRoute
  '/legal/creator-agreement': typeof LegalCreatorAgreementRoute
  '/legal/dmca': typeof LegalDmcaRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/me/downloads': typeof MeDownloadsRoute
  '/me/following': typeof MeFollowingRoute
  '/me/settings': typeof MeSettingsRoute
  '/me/subscriptions': typeof MeSubscriptionsRoute
  '/onboarding/creator': typeof OnboardingCreatorRoute
  '/dashboard': typeof DashboardIndexRoute
  '/me': typeof MeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/explore': typeof ExploreRoute
  '/for-creators': typeof ForCreatorsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/legal': typeof LegalRouteWithChildren
  '/me': typeof MeRouteWithChildren
  '/press': typeof PressRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roadmap': typeof RoadmapRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/c/$slug': typeof CSlugRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/announcements': typeof DashboardAnnouncementsRoute
  '/dashboard/files': typeof DashboardFilesRoute
  '/dashboard/payouts': typeof DashboardPayoutsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/subscribers': typeof DashboardSubscribersRoute
  '/dashboard/tiers': typeof DashboardTiersRoute
  '/legal/creator-agreement': typeof LegalCreatorAgreementRoute
  '/legal/dmca': typeof LegalDmcaRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/me/downloads': typeof MeDownloadsRoute
  '/me/following': typeof MeFollowingRoute
  '/me/settings': typeof MeSettingsRoute
  '/me/subscriptions': typeof MeSubscriptionsRoute
  '/onboarding/creator': typeof OnboardingCreatorRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/me/': typeof MeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/changelog'
    | '/contact'
    | '/dashboard'
    | '/explore'
    | '/for-creators'
    | '/forgot-password'
    | '/help'
    | '/legal'
    | '/me'
    | '/press'
    | '/pricing'
    | '/reset-password'
    | '/roadmap'
    | '/blog/$slug'
    | '/c/$slug'
    | '/dashboard/analytics'
    | '/dashboard/announcements'
    | '/dashboard/files'
    | '/dashboard/payouts'
    | '/dashboard/settings'
    | '/dashboard/subscribers'
    | '/dashboard/tiers'
    | '/legal/creator-agreement'
    | '/legal/dmca'
    | '/legal/privacy'
    | '/legal/terms'
    | '/me/downloads'
    | '/me/following'
    | '/me/settings'
    | '/me/subscriptions'
    | '/onboarding/creator'
    | '/dashboard/'
    | '/me/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/changelog'
    | '/contact'
    | '/explore'
    | '/for-creators'
    | '/forgot-password'
    | '/help'
    | '/legal'
    | '/press'
    | '/pricing'
    | '/reset-password'
    | '/roadmap'
    | '/blog/$slug'
    | '/c/$slug'
    | '/dashboard/analytics'
    | '/dashboard/announcements'
    | '/dashboard/files'
    | '/dashboard/payouts'
    | '/dashboard/settings'
    | '/dashboard/subscribers'
    | '/dashboard/tiers'
    | '/legal/creator-agreement'
    | '/legal/dmca'
    | '/legal/privacy'
    | '/legal/terms'
    | '/me/downloads'
    | '/me/following'
    | '/me/settings'
    | '/me/subscriptions'
    | '/onboarding/creator'
    | '/dashboard'
    | '/me'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/changelog'
    | '/contact'
    | '/dashboard'
    | '/explore'
    | '/for-creators'
    | '/forgot-password'
    | '/help'
    | '/legal'
    | '/me'
    | '/press'
    | '/pricing'
    | '/reset-password'
    | '/roadmap'
    | '/blog/$slug'
    | '/c/$slug'
    | '/dashboard/analytics'
    | '/dashboard/announcements'
    | '/dashboard/files'
    | '/dashboard/payouts'
    | '/dashboard/settings'
    | '/dashboard/subscribers'
    | '/dashboard/tiers'
    | '/legal/creator-agreement'
    | '/legal/dmca'
    | '/legal/privacy'
    | '/legal/terms'
    | '/me/downloads'
    | '/me/following'
    | '/me/settings'
    | '/me/subscriptions'
    | '/onboarding/creator'
    | '/dashboard/'
    | '/me/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  ChangelogRoute: typeof ChangelogRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ExploreRoute: typeof ExploreRoute
  ForCreatorsRoute: typeof ForCreatorsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRoute
  LegalRoute: typeof LegalRouteWithChildren
  MeRoute: typeof MeRouteWithChildren
  PressRoute: typeof PressRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RoadmapRoute: typeof RoadmapRoute
  CSlugRoute: typeof CSlugRoute
  OnboardingCreatorRoute: typeof OnboardingCreatorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-creators': {
      id: '/for-creators'
      path: '/for-creators'
      fullPath: '/for-creators'
      preLoaderRoute: typeof ForCreatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/': {
      id: '/me/'
      path: '/'
      fullPath: '/me/'
      preLoaderRoute: typeof MeIndexRouteImport
      parentRoute: typeof MeRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/onboarding/creator': {
      id: '/onboarding/creator'
      path: '/onboarding/creator'
      fullPath: '/onboarding/creator'
      preLoaderRoute: typeof OnboardingCreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/subscriptions': {
      id: '/me/subscriptions'
      path: '/subscriptions'
      fullPath: '/me/subscriptions'
      preLoaderRoute: typeof MeSubscriptionsRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/settings': {
      id: '/me/settings'
      path: '/settings'
      fullPath: '/me/settings'
      preLoaderRoute: typeof MeSettingsRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/following': {
      id: '/me/following'
      path: '/following'
      fullPath: '/me/following'
      preLoaderRoute: typeof MeFollowingRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/downloads': {
      id: '/me/downloads'
      path: '/downloads'
      fullPath: '/me/downloads'
      preLoaderRoute: typeof MeDownloadsRouteImport
      parentRoute: typeof MeRoute
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/dmca': {
      id: '/legal/dmca'
      path: '/dmca'
      fullPath: '/legal/dmca'
      preLoaderRoute: typeof LegalDmcaRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/creator-agreement': {
      id: '/legal/creator-agreement'
      path: '/creator-agreement'
      fullPath: '/legal/creator-agreement'
      preLoaderRoute: typeof LegalCreatorAgreementRouteImport
      parentRoute: typeof LegalRoute
    }
    '/dashboard/tiers': {
      id: '/dashboard/tiers'
      path: '/tiers'
      fullPath: '/dashboard/tiers'
      preLoaderRoute: typeof DashboardTiersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/subscribers': {
      id: '/dashboard/subscribers'
      path: '/subscribers'
      fullPath: '/dashboard/subscribers'
      preLoaderRoute: typeof DashboardSubscribersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/payouts': {
      id: '/dashboard/payouts'
      path: '/payouts'
      fullPath: '/dashboard/payouts'
      preLoaderRoute: typeof DashboardPayoutsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/files': {
      id: '/dashboard/files'
      path: '/files'
      fullPath: '/dashboard/files'
      preLoaderRoute: typeof DashboardFilesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/announcements': {
      id: '/dashboard/announcements'
      path: '/announcements'
      fullPath: '/dashboard/announcements'
      preLoaderRoute: typeof DashboardAnnouncementsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardAnnouncementsRoute: typeof DashboardAnnouncementsRoute
  DashboardFilesRoute: typeof DashboardFilesRoute
  DashboardPayoutsRoute: typeof DashboardPayoutsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSubscribersRoute: typeof DashboardSubscribersRoute
  DashboardTiersRoute: typeof DashboardTiersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardAnnouncementsRoute: DashboardAnnouncementsRoute,
  DashboardFilesRoute: DashboardFilesRoute,
  DashboardPayoutsRoute: DashboardPayoutsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSubscribersRoute: DashboardSubscribersRoute,
  DashboardTiersRoute: DashboardTiersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface LegalRouteChildren {
  LegalCreatorAgreementRoute: typeof LegalCreatorAgreementRoute
  LegalDmcaRoute: typeof LegalDmcaRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
}

const LegalRouteChildren: LegalRouteChildren = {
  LegalCreatorAgreementRoute: LegalCreatorAgreementRoute,
  LegalDmcaRoute: LegalDmcaRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
}

const LegalRouteWithChildren = LegalRoute._addFileChildren(LegalRouteChildren)

interface MeRouteChildren {
  MeDownloadsRoute: typeof MeDownloadsRoute
  MeFollowingRoute: typeof MeFollowingRoute
  MeSettingsRoute: typeof MeSettingsRoute
  MeSubscriptionsRoute: typeof MeSubscriptionsRoute
  MeIndexRoute: typeof MeIndexRoute
}

const MeRouteChildren: MeRouteChildren = {
  MeDownloadsRoute: MeDownloadsRoute,
  MeFollowingRoute: MeFollowingRoute,
  MeSettingsRoute: MeSettingsRoute,
  MeSubscriptionsRoute: MeSubscriptionsRoute,
  MeIndexRoute: MeIndexRoute,
}

const MeRouteWithChildren = MeRoute._addFileChildren(MeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  ChangelogRoute: ChangelogRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ExploreRoute: ExploreRoute,
  ForCreatorsRoute: ForCreatorsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRoute,
  LegalRoute: LegalRouteWithChildren,
  MeRoute: MeRouteWithChildren,
  PressRoute: PressRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RoadmapRoute: RoadmapRoute,
  CSlugRoute: CSlugRoute,
  OnboardingCreatorRoute: OnboardingCreatorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
