/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MeRouteImport } from './routes/me'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ForCreatorsRouteImport } from './routes/for-creators'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MeIndexRouteImport } from './routes/me.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as OnboardingCreatorRouteImport } from './routes/onboarding.creator'
import { Route as MeSubscriptionsRouteImport } from './routes/me.subscriptions'
import { Route as MeSettingsRouteImport } from './routes/me.settings'
import { Route as MeFollowingRouteImport } from './routes/me.following'
import { Route as MeDownloadsRouteImport } from './routes/me.downloads'
import { Route as DashboardTiersRouteImport } from './routes/dashboard.tiers'
import { Route as DashboardSubscribersRouteImport } from './routes/dashboard.subscribers'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardFilesRouteImport } from './routes/dashboard.files'
import { Route as DashboardAnnouncementsRouteImport } from './routes/dashboard.announcements'
import { Route as CSlugRouteImport } from './routes/c.$slug'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForCreatorsRoute = ForCreatorsRouteImport.update({
  id: '/for-creators',
  path: '/for-creators',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeIndexRoute = MeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MeRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const OnboardingCreatorRoute = OnboardingCreatorRouteImport.update({
  id: '/onboarding/creator',
  path: '/onboarding/creator',
  getParentRoute: () => rootRouteImport,
} as any)
const MeSubscriptionsRoute = MeSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => MeRoute,
} as any)
const MeSettingsRoute = MeSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MeRoute,
} as any)
const MeFollowingRoute = MeFollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => MeRoute,
} as any)
const MeDownloadsRoute = MeDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => MeRoute,
} as any)
const DashboardTiersRoute = DashboardTiersRouteImport.update({
  id: '/tiers',
  path: '/tiers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSubscribersRoute = DashboardSubscribersRouteImport.update({
  id: '/subscribers',
  path: '/subscribers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFilesRoute = DashboardFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnnouncementsRoute = DashboardAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => DashboardRoute,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/explore': typeof ExploreRoute
  '/for-creators': typeof ForCreatorsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/me': typeof MeRouteWithChildren
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/c/$slug': typeof CSlugRoute
  '/dashboard/announcements': typeof DashboardAnnouncementsRoute
  '/dashboard/files': typeof DashboardFilesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/subscribers': typeof DashboardSubscribersRoute
  '/dashboard/tiers': typeof DashboardTiersRoute
  '/me/downloads': typeof MeDownloadsRoute
  '/me/following': typeof MeFollowingRoute
  '/me/settings': typeof MeSettingsRoute
  '/me/subscriptions': typeof MeSubscriptionsRoute
  '/onboarding/creator': typeof OnboardingCreatorRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/me/': typeof MeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/for-creators': typeof ForCreatorsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/c/$slug': typeof CSlugRoute
  '/dashboard/announcements': typeof DashboardAnnouncementsRoute
  '/dashboard/files': typeof DashboardFilesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/subscribers': typeof DashboardSubscribersRoute
  '/dashboard/tiers': typeof DashboardTiersRoute
  '/me/downloads': typeof MeDownloadsRoute
  '/me/following': typeof MeFollowingRoute
  '/me/settings': typeof MeSettingsRoute
  '/me/subscriptions': typeof MeSubscriptionsRoute
  '/onboarding/creator': typeof OnboardingCreatorRoute
  '/dashboard': typeof DashboardIndexRoute
  '/me': typeof MeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/explore': typeof ExploreRoute
  '/for-creators': typeof ForCreatorsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/me': typeof MeRouteWithChildren
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/c/$slug': typeof CSlugRoute
  '/dashboard/announcements': typeof DashboardAnnouncementsRoute
  '/dashboard/files': typeof DashboardFilesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/subscribers': typeof DashboardSubscribersRoute
  '/dashboard/tiers': typeof DashboardTiersRoute
  '/me/downloads': typeof MeDownloadsRoute
  '/me/following': typeof MeFollowingRoute
  '/me/settings': typeof MeSettingsRoute
  '/me/subscriptions': typeof MeSubscriptionsRoute
  '/onboarding/creator': typeof OnboardingCreatorRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/me/': typeof MeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/explore'
    | '/for-creators'
    | '/forgot-password'
    | '/me'
    | '/pricing'
    | '/reset-password'
    | '/c/$slug'
    | '/dashboard/announcements'
    | '/dashboard/files'
    | '/dashboard/settings'
    | '/dashboard/subscribers'
    | '/dashboard/tiers'
    | '/me/downloads'
    | '/me/following'
    | '/me/settings'
    | '/me/subscriptions'
    | '/onboarding/creator'
    | '/dashboard/'
    | '/me/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/explore'
    | '/for-creators'
    | '/forgot-password'
    | '/pricing'
    | '/reset-password'
    | '/c/$slug'
    | '/dashboard/announcements'
    | '/dashboard/files'
    | '/dashboard/settings'
    | '/dashboard/subscribers'
    | '/dashboard/tiers'
    | '/me/downloads'
    | '/me/following'
    | '/me/settings'
    | '/me/subscriptions'
    | '/onboarding/creator'
    | '/dashboard'
    | '/me'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/explore'
    | '/for-creators'
    | '/forgot-password'
    | '/me'
    | '/pricing'
    | '/reset-password'
    | '/c/$slug'
    | '/dashboard/announcements'
    | '/dashboard/files'
    | '/dashboard/settings'
    | '/dashboard/subscribers'
    | '/dashboard/tiers'
    | '/me/downloads'
    | '/me/following'
    | '/me/settings'
    | '/me/subscriptions'
    | '/onboarding/creator'
    | '/dashboard/'
    | '/me/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ExploreRoute: typeof ExploreRoute
  ForCreatorsRoute: typeof ForCreatorsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  MeRoute: typeof MeRouteWithChildren
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  CSlugRoute: typeof CSlugRoute
  OnboardingCreatorRoute: typeof OnboardingCreatorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-creators': {
      id: '/for-creators'
      path: '/for-creators'
      fullPath: '/for-creators'
      preLoaderRoute: typeof ForCreatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/': {
      id: '/me/'
      path: '/'
      fullPath: '/me/'
      preLoaderRoute: typeof MeIndexRouteImport
      parentRoute: typeof MeRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/onboarding/creator': {
      id: '/onboarding/creator'
      path: '/onboarding/creator'
      fullPath: '/onboarding/creator'
      preLoaderRoute: typeof OnboardingCreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/subscriptions': {
      id: '/me/subscriptions'
      path: '/subscriptions'
      fullPath: '/me/subscriptions'
      preLoaderRoute: typeof MeSubscriptionsRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/settings': {
      id: '/me/settings'
      path: '/settings'
      fullPath: '/me/settings'
      preLoaderRoute: typeof MeSettingsRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/following': {
      id: '/me/following'
      path: '/following'
      fullPath: '/me/following'
      preLoaderRoute: typeof MeFollowingRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/downloads': {
      id: '/me/downloads'
      path: '/downloads'
      fullPath: '/me/downloads'
      preLoaderRoute: typeof MeDownloadsRouteImport
      parentRoute: typeof MeRoute
    }
    '/dashboard/tiers': {
      id: '/dashboard/tiers'
      path: '/tiers'
      fullPath: '/dashboard/tiers'
      preLoaderRoute: typeof DashboardTiersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/subscribers': {
      id: '/dashboard/subscribers'
      path: '/subscribers'
      fullPath: '/dashboard/subscribers'
      preLoaderRoute: typeof DashboardSubscribersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/files': {
      id: '/dashboard/files'
      path: '/files'
      fullPath: '/dashboard/files'
      preLoaderRoute: typeof DashboardFilesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/announcements': {
      id: '/dashboard/announcements'
      path: '/announcements'
      fullPath: '/dashboard/announcements'
      preLoaderRoute: typeof DashboardAnnouncementsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAnnouncementsRoute: typeof DashboardAnnouncementsRoute
  DashboardFilesRoute: typeof DashboardFilesRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSubscribersRoute: typeof DashboardSubscribersRoute
  DashboardTiersRoute: typeof DashboardTiersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnnouncementsRoute: DashboardAnnouncementsRoute,
  DashboardFilesRoute: DashboardFilesRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSubscribersRoute: DashboardSubscribersRoute,
  DashboardTiersRoute: DashboardTiersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface MeRouteChildren {
  MeDownloadsRoute: typeof MeDownloadsRoute
  MeFollowingRoute: typeof MeFollowingRoute
  MeSettingsRoute: typeof MeSettingsRoute
  MeSubscriptionsRoute: typeof MeSubscriptionsRoute
  MeIndexRoute: typeof MeIndexRoute
}

const MeRouteChildren: MeRouteChildren = {
  MeDownloadsRoute: MeDownloadsRoute,
  MeFollowingRoute: MeFollowingRoute,
  MeSettingsRoute: MeSettingsRoute,
  MeSubscriptionsRoute: MeSubscriptionsRoute,
  MeIndexRoute: MeIndexRoute,
}

const MeRouteWithChildren = MeRoute._addFileChildren(MeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ExploreRoute: ExploreRoute,
  ForCreatorsRoute: ForCreatorsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  MeRoute: MeRouteWithChildren,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  CSlugRoute: CSlugRoute,
  OnboardingCreatorRoute: OnboardingCreatorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
